## Assignment Question

In [1]:
import numpy as np
list_ = [1,2,3,4,5]
array_list = np.array(object = list_)

In [2]:
print(array_list)

[1 2 3 4 5]


In [3]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


__Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.__

__Ans)__ __Yes, there is a difference in the data type of variables list_ and array_list.list_ is a Python list object__ while array_list is a NumPy array object.You can print the data types of both variables using the type() function as follows:

__Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.__

In [4]:
for element in list_:
    print(type(element))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [5]:
for element in array_list:
    print(type(element))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [6]:
array_list = np.array(object = list_, dtype = int)

In [7]:
for element in list_:
    print(type(element))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [8]:
for element in array_list:
    print(type(element))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [9]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [11]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [12]:
num_array.size

6

In [13]:
num_array.shape

(2, 3)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [15]:
c=np.zeros((3,3))
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:

identity_matrix = np.eye(5)

print(identity_matrix)

-------------------------------------------------------------------------------------------- __End__----------------------------------------------------------------------------------------------------------------